baseURL = 'https://hugosimpletest2.vercel.app/'
languageCode = "ja"
title = "Your Site Title"
theme = "hugo-bearblog"
sectionPagesMenu = 'main'



[[module.mounts]]
source = 'static'
target = 'static'

[[module.mounts]]
source = 'images'
target = 'static/images'


[params]
    [params.author]
    intro = "hello"
    description = "yoyoyo"